- src/Zip/ZipConstants.cs
> Fix ArgumentException from Encoding::GetEncoding() in creating a ZipFile

- src/Zip/ZipFile.cs
Correct the zip specification version by only checking the lower bits; otherwise it will fail to unzip some zipped files via FastZip.ExtractZip.
> Update ZipFile.cs to correct the zip specification version.

- src/ICSharpCode.SharpZLib.csproj
When attempting to use ICSharpCode.SharpZLib.csproj as part of a VS 2013 solution, an error occurs informing you that a one-way upgrade is required for compatibility.  Adding the ToolsVersion property to the project file allows the project to be added to more recent VS solutions in a way that shouldn't break existing builds or solutions.
> Allow the project file to be added to a VS 2013 solution

- src/Tar/TarHeader.cs
- src/Tar/TarOutputStream.cs
Was using the library to generate debian packages which use Tar inside. Files with names longer than 100 symbols were preventing the package from installing - dpkg couldn't copy the files with the long names. Looking at the specification and Tars generated on Linux with default tools I found several bugs:
- Ustar format supports names up to 100 symbols. That is, if a name is exactly 100 symbols you don't need to write terminating symbol. SharpZipLib truncates names to 99 symbols
- "@LongLink" should have default 644 mode. SharpZipLib doesn't specify it
- "@LongLink" should have user ID, user name, group ID and group name from the entry it belongs to. SharpZipLib doesn't specify them
> Fix tar long names

- src/Zip/ZipEntry.cs
(localHeader ||) was deleted, because actually there is no specific difference with reading sizes between local header & central directory 
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT 
...
4.4  Explanation of fields
...
4.4.8 compressed size: (4 bytes)
4.4.9 uncompressed size: (4 bytes)
The size of the file compressed (4.4.8) and uncompressed,
(4.4.9) respectively.  When a decryption header is present it 
will be placed in front of the file data and the value of the
compressed file size will include the bytes of the decryption
header.  If bit 3 of the general purpose bit flag is set, 
these fields are set to zero in the local header and the 
correct values are put in the data descriptor and
in the central directory.  If an archive is in ZIP64 format
and the value in this …
> problem with minizip implementation

- src/Zip/ZipFile.cs
When reading a stored file, ZipFile returns a PartialInputStream
directly instead of wrapping it with a decompression layer.
PartialInputStream handles sharing the underlying stream among
multiple threads by calling Seek() before each read.
Unlike Microsoft's reference implementation, Mono's FileStream
flushes its internal read buffer on every Seek.
> Fix severe perf degradation reading Stored file in Mono

- ICSharpCode.SharpZipLib/Tar/TarArchive.cs
- ICSharpCode.SharpZipLib/Tar/TarHeader.cs
- ICSharpCode.SharpZipLib/Tar/TarInputStream.cs
- ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- ICSharpCode.SharpZipLib/Zip/ZipExtraData.cs
- ICSharpCode.SharpZipLib/Zip/ZipFile.cs
I've been maintaing a fork of SharpZipLib with a number of small tweaks and bugfixes. This code has been in heavy use for over a year in [Zero Install](http://0install.de/) and is available on NuGet as [ICSharpCode.SharpZipLib.Patched](https://www.nuget.org/packages/ICSharpCode.SharpZipLib.Patched/).
For the pull request I have rebased everything on the current master and removed anything that would change the publicly visible API. This also includes the commit from #18, which I've been using in my fork.
> Multiple tweaks and bugfixes

- src/Zip/ZipFile.cs
Some rogue zip creators fail to set a non-zero local header size in ExtraData causing SharpZLib to reject them, this patch allows the library to tolerate that particular oversight like most other libraries.
> Tolerate 0-value (missing) local size headers.

- ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
After VS2015 Update 3 was installed, the csproj wont compile any more. "Microsoft.Common.props" needs to be included in the csproj file. This PR adds this.
> Fix build on VS2015 Update 3

- ICSharpCode.SharpZipLib.Tests/GZip/GZipTests.cs
- ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
- ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs
- ICSharpCode.SharpZipLib/Tar/TarHeader.cs
- ICSharpCode.SharpZipLib/Tar/TarOutputStream.cs
- ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs
Would like to try optimizations on stream read virtual calls, for which I need to check the changes with tests. Turned out that 16 of them were failing out of the box. Fixed 10 which had more or less obvious technical issues. The idea of the remaining tests is not so straightforward.
This applies to WinNT platform.
> Fixed 10 Tests (out of 16 Failing)

- ICSharpCode.SharpZipLib/Zip/Compression/PendingBuffer.cs
If AlignToByte() (or a procedure similar to that in Flush()) is not done within ToByteArray(), the bits variable may contain up to 15 bits not present in buffer_ which could result in data truncation. I have added AlignToByte() on the assumption that ToByteArray() will only be called when all output to PendingBuffer is complete.
> PendingBuffer ToByteArray() to return all bytes

- src/Zip/Compression/Streams/InflaterInputStream.cs
related to issue #80 
just simply throw exception is enough, to get the real stream size before reading, should use entry.size.
> the stream is not seek-able, access to Length should return exception

- appveyor.yml
This tiny change can get appveyor going again, as shown here:
https://ci.appveyor.com/project/xied75/sharpziplib/build/1.0.2
Ref: http://help.appveyor.com/discussions/problems/5145-build-failing
> tiny change to make appveyor back to work

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
Update framework targets to netstandard2 and net45
> Update framework targets to netstandard2 and net45

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
The original target was only netstandard1.3 which is only supported on the full net framework 4.6 or higher.
The new csproj format allows easy multi-framework support so it now builds for netstandard1.3 and net45. 
> Restore support for NET4.5

- src/ICSharpCode.SharpZipLib/Core/InvalidNameException.cs
- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
Prevents files from being written outside of target directory when invoked from `FastZip.ExtractZip()`.
Attempting to extract a file that has a path traversing outside of the `targetDirectory` will throw and `InvalidNameException` unless explicitly overridden:
```.cs
new FastZip().ExtractZip(archive, targetDirectory, FastZip.Overwrite.Never,
null, "", "", true, allowParentTraversal: true);
```
> Restrict path traversal on FastZip extraction (fixes #232)

- src/ICSharpCode.SharpZipLib/Zip/Compression/Inflater.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/InflaterDynHeader.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/StreamManipulator.cs
If no end symbol is reached before the memory in the output window runs out, it will just be flushed to the output and reset the window without progressing. This causes an infinite loop on bad Huffman data (32768 consecutive literals).
This is caused by allowing bad values into the table and this fix only prevents the infinite loop, not the real cause.
> Fix infinite loop on bad literal data (Issue #229)

- src/ICSharpCode.SharpZipLib/GZip/GZip.cs
- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
Fixes XML Comment for `GZip.Compress` and add supposed functionality by optional argument.
Fixes #151 without breaking backwards compability. 
> Fix Gzip.Compress arguments

- src/ICSharpCode.SharpZipLib/Checksum/Adler32.cs
- src/ICSharpCode.SharpZipLib/Checksum/BZip2Crc.cs
- src/ICSharpCode.SharpZipLib/Checksum/Crc32.cs
- src/ICSharpCode.SharpZipLib/Checksum/IChecksum.cs
- src/ICSharpCode.SharpZipLib/GZip/GzipInputStream.cs
- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/DeflaterEngine.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Inflater.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Checksum/ChecksumTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs
> Convert crc checking to use ArraySegment for parameter validation.

- src/ICSharpCode.SharpZipLib/Tar/TarInputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
Attempt to read two end blocks when reading tararchive.
> Attempt to read two end blocks when reading tararchive (Fixes #213)

- appveyor.yml
Correctly works with the new SDK .csproj format and netcore2 testing (unsupported by appveyor?)
Builds nuget packages with the commit as the suffix.
> Add new appveyor.yml

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntryFactory.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/StringTesting.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
Commit 2c458be replaced the default code page with UTF-8, but ZipEntry.IsUnicodeText is still set to `false` by default.
This makes it the default behaviour of SharpZipLib to create zip files that *claim* they are **not** coded using UTF-8 (but instead with what is presumed to be the locale default code page), but still containing  UTF-8 encoded file names.
This PR will rectify that by setting the `ZipEntry.IsUnicodeText` default based on what `ZipStrings.CodePage` (previously called `ZipConstants.DefaultCodePage`) is set to.
This also moves the string transcoding from `ZipConstants` to `ZipStrings` as I could not let it stay inside a class obviously named for another purpose.
There are still wrappers for all public functionality that provides full backwards compability.
_I certify that I …
> Correctly handle Unicode strings

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
> Update csproj for v1.0.0 stable

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
> Add AES encryption tests

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs
> Fixed issue by using lower 16 bytes as IV for AES256

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
> Add test for AES decompress

- README.md
Trying to make it easier to find the live docs.
> Add link to API in README (fixes #189)

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
This adds roughly 100KiB to the nuget package size but allows library consumers to get a full stack trace and step through the library code. This will hopefully help to give a better understanding about what happens when something goes wrong and allows for better issue descriptions.
Fixes #269 
> Add SourceLink support

- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/StringTesting.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
Issues #274 and #278 are fixed, but there's an another issue with Unicode test samples.
It seems, that Greek and Arabic samples are incorrect. I've added a workaround in https://github.com/EvilBeaver/SharpZipLib/commit/887e10def8eec0cd41fa531b9f4dd1f8c1c39227
Probably, old-code tests weren't failing, because ZipStrings.SystemDefaultCodePage was set to 65001, which is seems to be returned by default from Encoding.GetEncoding(0) on net.core
> Fix 274 and 278

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs
As long as `inputCount` is 0, no actual work has to be done inside `TransformFinalBlock` so no exception should be thrown.
This should fix AES decryption since the last block is handled by `TransformBlock` as far as I can tell.
> Prevent exception in ZipAESTransform

- src/ICSharpCode.SharpZipLib/Zip/Compression/Deflater.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/DeflaterEngine.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Inflater.cs
As a result of the discussion here:
https://github.com/icsharpcode/SharpZipLib/issues/289
I've created this pull request with a possible solution to not calculate the Adler checksum if it's not necessary.
I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License.
> Do not calculate Adler checksum if it is not necessary.

- src/ICSharpCode.SharpZipLib/Checksum/Adler32.cs
- test/ICSharpCode.SharpZipLib.Tests/Checksum/ChecksumTests.cs
> Revert Adler32 changes and add test

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
`ZipFile.FindExistingUpdate(ZipEntry)` would always return -1 for directory `ZipEntry`s due to using `GetTransformedFileName` on all `ZipEntry`s. As a result, `ZipFile.Delete(ZipEntry)` would always throw an exception when passed a directory `ZipEntry`. The fix is to call `GetTransformedDirectoryName` for directory `ZipEntry`s.
I updated the test `AddAndDeleteEntries` in `ZipFileHandling.cs` to add and delete a directory; this test failed without the change to `ZipFile.FindExistingUpdate`.
I believe issue #290 is related.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT …
> Fix exception from deleting a directory ZipEntry in a ZipFile

- src/ICSharpCode.SharpZipLib/Checksum/BZip2Crc.cs
- src/ICSharpCode.SharpZipLib/Checksum/Crc32.cs
Another fix for this issue: https://github.com/icsharpcode/SharpZipLib/issues/289
> Performance enhancement by skipping the (unnecessary) checks in ArraySegment

- src/ICSharpCode.SharpZipLib/Core/StreamUtils.cs
- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Streams.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
Some changes to the reading of AES encrypted zips, to try to better handle reading from streams which might onyl return part of the requested data.
Refs https://github.com/icsharpcode/SharpZipLib/issues/303, posible alternative approach to https://github.com/icsharpcode/SharpZipLib/pull/305
> Changes to AES zip handling to better handle stream read attempts only returning partial data

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
When running the unit tests, I've seen a couple of failures in the encryption tests that seem to be simply because the temp file path has a space in it, which causes issues when invoking 7-zip on the file.
Perhaps it needs quotes putting around the test file path?
> When invoking 7-zip in the tests, put quotes around the path to the test file

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
FastZip.ExtractZip uses ZipFile internally and might fall over #144 when working with a corrupt file (whereby it closes the input stream even if isStreamOwner is set to false when an error occurs).
Try to avoid that by using the new ZipFile constructor and setting leaveOpen as required.
> Change FastZip.ExtractZip to use the new ZipFile constructor to set isStreamOwner, rather than setting the property after construction

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
CompressionMethod.BZip is curently defined as 11, but it seems that it should actually be 12
> Change value of CompressionMethod.Bzip2 from 11 to 12

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
WriteCentralDirectoryHeader currently checks IsZip64Forced when deciding to write -1 to the base size fields [ZipFile.cs#L2174](https://github.com/Numpsy/SharpZipLib/blob/0fff917d8ef61e9cd0b9b8574301498a6416e0bf/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L2174) but not when writing the extra data [ZipFile.cs#L2208](https://github.com/icsharpcode/SharpZipLib/blob/4f541a404f324bd882bc1e8ecd1182c05909b08a/src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs#L2208), so the length doesn't get written.
This changes it to check in both places, and adds a test
Assuming that the length field and extra data should always be in sync (would you ever set size to -1 and not write the extra data?), might be better to set some 'wantsExtraSize' flags rather than checking ((entry.Size >= 0xffffffff) || otherFlags) …
> Fix writing extra data when updating Zip64 entries

- src/ICSharpCode.SharpZipLib/Zip/Compression/InflaterHuffmanTree.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/ThreadEx.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipCorruptionHandling.cs
> Throw exception when attempting to read a zero code length symbol

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
Possible fix for #322 - Change ZipOutputStream.CloseEntry() to set up AESAuthCode itself when the compression method is 'Stored' (it's normally done by DeflatorOutputStream.Finish(), which isn't called in this case).
> Change ZipOutputStream.CloseEntry() to work for AES encrypted Stored entries

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Create a zip archive with specific permissions, such as the executable flag, using the `ExternalAttributes` property. The Linux `unzip` command only applies such permissions if the zip entry indicates the file was added by a Linux host-system.
Expose the more specific `ZipEntry` constructors that allow controlling the version number and host-system information. Ensure this information is used when creating the zip archive.
1. Changed access level from `internal` to `public` on constructors for `ZipEntry`. This allows setting the `madeByInfo` value.
1. Changed `VersionMadeBy` property to return the entire `ushort`. This is required by `ZipFile` and `ZipOutputStream` to write the correct value.
1. Fixed `HostSystem` property to clear out the upper byte where the host system information is …
> Ability to mimic a zip file created by a Linux file-system.

- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
Ensures that, if the root path is an empty string, the library will not try to take a substring of the file name (and cause the first character of the filename to be truncated).
> Treat empty string as no RootPath in TarArchive (fixes #334)

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
This is an attempt to handle #324 by changing ZipAESStream.Read() to buffer the transformed data in cases where the length of the data to read is less than the crypto block size (or not a multiple of the block size).
When reading full blocks, it transforms directly into the output buffer so the data doesn't need to bew copied again.
Not sure if it's best to do it like this, or to buffer the data seperately in this case?
(also, fwiw, I originally saw this issue when looking at #315 and then reproed it with Stored files, so changing this will help with that as well).
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My …
> Change ZipAESStream to handle reads of less data than the AES block size

- ICSharpCode.SharpZipLib.sln
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Checksum/Adler32.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Checksum/BZip2Crc.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Checksum/Crc32.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/ICSharpCode.SharpZipLib.Benchmark.csproj
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Program.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Zip/ZipInputStream.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Zip/ZipOutputStream.cs
As I proposed in #328, this PR adds a benchmarks project using BenchmarkDotNet, with a few simple benchmarks for the CRC handling and zip input/output streams that i did when testing the proposed CRC changes and playing with .NET Core 3.
Could be useful for testing performance related changes in the future? It's a start anyway.
> Add a benchmarks project using BenchmarkDotNet

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
Change ZipEntry.ProcessAESExtraData to not set the StrongEncryption flag for WinZipAes encrypted entries.
As mentioned in #317, setting the StrongEncryption flag in ProcessAESExtraData doesn't seem correct.
This changes that, and rearranges CreateAndInitDecryptionStream to check for the compression method being WinZipAES rather than for the StrongEncryption flag being set.
This will throw if the archive is really using the PKWare strong encryption, which I think is correct if that isn't actually supported?
Related to this: I'm not sure if the 
```
versionToExtract = ZipConstants.VERSION_AES
```
in ProcessAESExtraData is correct either (what happens if the existing version is greater than that?). Maybe needs a seperate change?
_I certify that I own, and have sufficient rights to …
> Do not set the StrongEncryption flag for WinZipAes encrypted entries

- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
This pulls part of the change for #333 into a seperate PR (just the piece that sets the ZipEntry compression method via the constructor rather than setting the property after construction).
> Change ZipInputStream.GetNextEntry to set the entry compression method via its constructor.

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
They aren't currently used by the library, but for completeness and testing purposes add the LZMA and PPMd compression methods to ZipConstants (values taken from section 4.4.5 of the AppNote).
> Add LZMA and PPMd to the Zip CompressionMethod enum

- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
refs #321 - change TarArchive.ExtractEntry to dispose of output file streams in a finally block, in case an exception occurs. 
(pretty simple change, but it looks like changing the indentation makes the diff viewer make the change look greater than it is).
Also adds a unit test that failed previously and passes now.
> Change TarArchive.ExtractContent() to dispose of output streams in case of an exception

- test/ICSharpCode.SharpZipLib.TestBootstrapper/ICSharpCode.SharpZipLib.TestBootstrapper.csproj
- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
I tried running code coverage on the unit tests with Visual Studio 2019 and found that it didn't work, which I think is down to limitations of the old packages with the .NET Core tests.
Any objections to updating the SDK and NUnit packages in the test projects to the current versions where it works ok?
> update test sdk and nunit packages to the curent versions.

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipCorruptionHandling.cs
Possible change for #357 - in ZipFile.ReadEntries, always look for the zip64 central directory and use it if present, rather than only looking if we think we need it.
This change will still throw if it thinks the zip64 directory is required but can't find it (same logic there as before).
The change is sufficient to get the file from #356 loading successfully without causing any issues with the existing unit tests, but doesn't add any more tests as I don't have an appropriate test file to hand (the one linked from #356 being too large to use for a unit test)
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My …
> Change ZipFile.ReadEntries to always look for the Zip64 central directory

- src/ICSharpCode.SharpZipLib/BZip2/BZip2Exception.cs
- src/ICSharpCode.SharpZipLib/Core/Exceptions/SharpZipBaseException.cs
- src/ICSharpCode.SharpZipLib/Core/Exceptions/StreamDecodingException.cs
- src/ICSharpCode.SharpZipLib/Core/Exceptions/StreamUnsupportedException.cs
- src/ICSharpCode.SharpZipLib/Core/Exceptions/UnexpectedEndOfStreamException.cs
- src/ICSharpCode.SharpZipLib/Core/Exceptions/ValueOutOfRangeException.cs
- src/ICSharpCode.SharpZipLib/Core/InvalidNameException.cs
- src/ICSharpCode.SharpZipLib/GZip/GZipException.cs
- src/ICSharpCode.SharpZipLib/Lzw/LzwException.cs
- src/ICSharpCode.SharpZipLib/Tar/TarException.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipException.cs
- test/ICSharpCode.SharpZipLib.Tests/Serialization/SerializationTests.cs
refs #365 :
-Mark the custom exception types as Serializable
-Add the constructor overloads needed for deserialization
-Add unit tests for (de)serialization
> Make the custom exception types serializable

- src/ICSharpCode.SharpZipLib/GZip/GzipInputStream.cs
PR #225 introduced a new throw that did not test the right values. The case of stream EOF is handled when attempting to fill the input buffer and `inf.RemainingInput` should not be used for this. Instead, the reason for the test getting stuck is that it attempts to read 0 bytes from the stream. Since the loop tries to read data until it can read at least one byte, it's forever stuck (since attempting to read 0 bytes never returns more than 0 bytes read).  
The use case for supplying 0 as `count` is probably slim, but at least now we're not stuck in an infinite loop.
Corr for #225
Fixes #360
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product …
> Remove bad GZipException and don't loop forever on 0 reads

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
Possible fix for #341 - don't call CleanName in the ZipEntry constructor.
This matches the doc comments on one of the ZipEntry constructors which says that the name format isn't enforced anyway. Not sure if this causes any gaps where names won't be validated on creating zips - not sure whether it'd be better to do some validation for 'new' ZipEntries, but just not for ones created internally when reading an existing zip?
Also marked as WIP because on further testing it seems that a lot of the validation for the characters in paths has been removed from .NET Core, meaning that the exception described in #341 might only happen in the full version of .NET (and as the unit tests are only built as Core, the exception won't be seen there).
_I certify that I own, and have sufficient rights to …
> Don't call CleanName from the ZipEntry constructor.

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/RingBuffer.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
Since #225 added forced flushing to `DeflaterOutputStream` it will run the deflate state machine even if it's not supposed to be used. This did not happen before since it were always in a state where it did not need more data when using `CompressionMethod.Stored`.
By overriding the `Flush()` method in `ZipOutputStream` we can skip the forced deflate flush when it isn't used.
Should fix #398 and #391 
> Skip forced Deflate flush when using Stored compression

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
#403 / #375 - the Zip64 end of central directory locator has a fixed 20 byte length, but the calls to LocateBlockWithSignature were specifying a fixed size of 0 and a dynamic size of 0x1000, which meant that the signature bytes could incorrectly be matched in a location other than where they should be (20 bytes prior to the end of central directory signature)
> When searching for the Zip64 end of central directory locator, pay attention to its fixed size.

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Streams.cs
Possible fix for #379, using the change to InflaterInputStream suggested there.
I'm not certain if its best to do the extra check in the inflator code or in gzipinputstream - putting it in the lower level code could effect the handling of Zip files as well, but i'm not certain if the issue can effect ZipInputStream in the same way as GZipInputStream.
> Better handle baseStreams closing themselves unexpectedly

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
It's currently built with the 1.0.0-beta2 version - any reason to not update to the release version?
> Update Microsoft.SourceLink.GitHub to the 1.0.0 release version

- README.md
The forum at community.sharpdevelop.net doesn't seem to exist any more, so no need to retain a link to it in the documentation?
> Remove the link to the sharpdevelop forum from readme.md

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
As suggested in #385, make the Add(IStaticDataSource dataSource, ZipEntry entry) function in ZipFile throw NotSupportedException if you try to add an entry with AES encryption set, rather that silently using ZipCrypto instead.
> Make ZipFile.Add throw NotSupportedException when trying to add an AES encrypted entry

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
… to validate the method themselves, and throw consistent exceptions for unsupported methods
Related to the discussions in #333 and some of the issues that occur when adding extra compression methods due to using ZipEntry for compression method validation:
There are currently the following methods in ZipFile to add a new entry and specify a compression method to use:
```cs
public void Add(string fileName, CompressionMethod compressionMethod, bool useUnicodeText);
public void Add(string fileName, CompressionMethod compressionMethod);
public void Add(IStaticDataSource dataSource, string entryName, CompressionMethod compressionMethod);
public void Add(IStaticDataSource dataSource, string entryName, CompressionMethod compressionMethod, bool useUnicodeText);
public void Add(IStaticDataSource …
```
> Validate compression method in all ZipFile.Add overloads

- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
refs #434 - multi-target the unit test project such that the unit tests can be run against both .NET and .NET Core.
It targets net 4.6 rather than 4.5 (to match the library build) because the System.Text.Encoding.CodePages package doesn't contain a 4.5 build.
An alternative there might be to only import the package in the Core build and ifdef the calls to Encoding.RegisterProvider, as the extra code pages should be available on the full framework by default anyway?
> multi-target the unit tests as .NET Core 2.0 and .NET 4.6

- benchmark/ICSharpCode.SharpZipLib.Benchmark/ICSharpCode.SharpZipLib.Benchmark.csproj
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Program.cs
I was going to look at adding some direct benchmarks for the deflate streams, and thought I may as well update BenchmarkDotNet to the current version
> Update the benchmark project to BenchmarkDotNet 0.12.1

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
I noticed when looking at #427 that the encryption unit tests that test created archives with 7-zip test AES encryption, but not ZipCrypto encryption.
Any reason not to test both?
Also refactors the tests a little to turn the stored/deflated tests into test cases instead of duplicating the tests.
> Add a ZipCrypto/7zip interop test to the ZipEncryptionHandling tests

- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
A piece of #381 broken out into its own PR - rather than storing the compression method of the current entry as an int and casting in multiple places, store it as a CompressionMethod with one cast and then use it directly elsewhere.
> In ZipInputStream, store the entry compression method as a CompressionMethod, instead of storing it as an int and casting it in multiple places

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
When writing the local/central directory entries in ZipFile, use the CompressionMethodForHeader property of ZipEntry instead of the CompressionMethod property, in order to handle the case where the entry method is WinZipAes.
Add a couple of extra unit tests, which both try to verify using SharpZipLib locally (#317 aside) and with 7-Zip.
refs #439 
> Use ZipEntry.CompressionMethodForHeader when writing the header entries

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
It is not necessary to specify the explicit path for `<DocumentationFile>`, just setting `<GenerateDocumentationFile>` to `true` will generate the documentation file in the default locations.
> Simplify Documentation generation

- src/ICSharpCode.SharpZipLib/BZip2/BZip2.cs
Pretty trivial, but just something I noticed while looking at the code - throwing a base Exception for a null parameter doesn't seem ideal - ArgumentNullException with the parameter name specified seems better?
> Change the BZip2 Compress/Decompress functions to throw ArgumentNullxception rather than Exception when null stream parameters are provided

- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
refs #123 - the described issue already seems to have been fixed, but here's a unit test for calling Write with a zero byte buffer in case it's useful.
> Unit test for issue #123

- README.md
Just a small tweak to readme.md to add a Nuget badge along side the build and gitter ones, to make it easily visible.
I was wondering it it's possible to have one that points to the AppVeyor CI nuget feed, but I don't see it in the docs, and shields.io only seems to mention nuget.org and MyGet.
> Add a Nuget badge to readme.md

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEntryHandling.cs
Changes:
- Store `ZipEntry.DateTime` in dedicated backing field.  
This allows reading values with a higher resolution than DOS time (2 second accuracy).
- Fix getting unix modification time in ZIP files.  
I was the contributor that originally added that if-check, but I unfortunately was mistaken. InfoZIP actually does respect a file's modification time, even if the access time and/or creation time are not set.
> Improve support for Unix timestamps in ZIP archives

- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
When I was looking at #454 I noticed there didn't seem to be a unit test for adding empty folders to new archives in FastZip (there is one for extracting empty folders), so I added a simple one.
(test tries it with both encrypted and non-encrypted archives)
> Unit test for FastZip adding empty folders to archives

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
This is useful when passing the object to C code, as applications often seek() to the end and tell() to find out the length of a stream.
> Allow seeking a PartialInputStream to the very end.

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
A test for the issue from #465 - test with several read sizes, both smaller and larger than the AES block size
> Improve the ZipFileStoreAesPartialRead test to test multiple block sizes

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
copyCount was being computed but not passed to Array.Copy(), which caused an
exception to be thrown when enough bytes were read from an encrypted stream.
> Fixed bug in ZipAESStream.ReadBufferedData.

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
I noticed that the 7-zip interop tests weren't running in the .Net 4.6 test run, with the error
```
"The Process object must have the UseShellExecute property set to false in order to redirect IO streams."
```
According to the Microsoft docs @ https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=netframework-4.8, UseShellExecute is false by default on .Net Core but true on .Net, so - may as well set if to false all the time ourselves.
> Fix the 7-zip interop tests in the .Net 4.6 test build

- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Found by accident - a couple of doc comments have exception elements with a 'name' attribute rather than 'cref' attribute.
> fix a couple of exception doc comments

- test/ICSharpCode.SharpZipLib.Tests/BZip2/Bzip2Tests.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
Rather trivial but: the NUnit analyzer suggests that a few asserts have the expected/actual values backwards.
> Fix some unit test asserts

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
refs #471 
Two changes:
1) In the current setter for ```ZipFile.Password```, it only updates the ```rawPassword_``` member if the new value isn't null or empty.
That seems wrong to me in general, as it means that setting the password to a value and then setting it to null would leave the member set to the old value?
This PR changes it to always just save the new value in ```rawPassword_```.
2) In CreateAndInitDecryptionStream, throw if the string password is null, but proceed to try to use it if the string is empty.
The current code uses ```HasKeys``` to check that it has the keys, but then uses the password instead, which doesn't sound quite right? (though looking at the way ```KeysRequired```/```OnKeysRequired``` I'm not sure if it works to get the password (rather than the keys') for …
> Allow ZipFile to accept empty strings as passwords when decrypting AES entries

- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipTests.cs
refs #382 - An an override of Flush() to GZipOutputStream to ensure the GZip header is always written before any data is flushed to the output stream.
I'm not entirely sure that there aren't any other issues occuring the described example or with the way flushing is handled, but ensuring the header is written before flushing fixes the tests and seems a reasonable thing to do.
>  An an override of Flush() to GZipOutputStream to ensure the headers are writen before flushing

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
Was looking at #112 and noticed that there is an overload of ZipFile.Add that takes an alternate file name, but that there are no unit tests for it, so thought I may as well add one.
> Add a unit test for the Add(string fileName, string entryName) overload of ZipFile.Add

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
When extracting a zip with FastZip with the RestoreDateTimeOnExtract set to true, restore the LastWriteTime on directories as well as files.
Only resets the timestamp on folders that it creates itself, not if extracting into an already existant folder structure.
refs #426 
> Restore directory timestamps when extracting with FastZip

- src/ICSharpCode.SharpZipLib/Core/NameFilter.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
A spin off of #449 to fix some CA1200 "Avoid using cref tags with a prefix" warnings.
The prefixes in the code are all for simple system types, so going from the MS docs @ 
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1200?view=vs-2019, they don't seen to be needed?
As well as fixing the warnings, it also makes VS intellisense display type information, where it doesn't before.
> Fix CA1200 code analyzer warnings

- src/ICSharpCode.SharpZipLib/Tar/InvalidHeaderException.cs
- test/ICSharpCode.SharpZipLib.Tests/Serialization/SerializationTests.cs
I was looking at some code analyzer results of the build, and one of the things it suggested was that InvalidHeaderException should be [Serializable], given that it derives from a serializable type (TarException).
I don't know why this wasn't done along with the others, aside from having been overlooked?
> Make InvalidHeaderException serializable

- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Equivalent of #421, but for ZipOutputStream.
I added this to throw NotImplementedException, and then wondered again if it should be that or NotSupportedException :-(.
PR Doesn't add a unit test as the CompressionMethod property setter on ZipEntry currently prevents it, so the only way to try it would be to use a ZipEntry with a different type from an existing file.
> Change ZipOutputStream.PutNextEntry to explicity validate the requested compression method

- src/ICSharpCode.SharpZipLib/Checksum/BZip2Crc.cs
- src/ICSharpCode.SharpZipLib/Core/FileSystemScanner.cs
- src/ICSharpCode.SharpZipLib/Lzw/LzwInputStream.cs
- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
- src/ICSharpCode.SharpZipLib/Tar/TarOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/DeflaterEngine.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/InflaterInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntryFactory.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipExtraData.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipHelperStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
A quick pass at fixing a few things shown by a visual studio spell checker addon (probably not all of them as there's a lot of noise from variable names, peoples names, etc), plus some might depend on which english dictionary is being used!
> have a pass at fixing some spelling errors in comments

- src/ICSharpCode.SharpZipLib/Zip/ZipNameTransform.cs
Is there a need to remove leading/trailing slashes with manual loops rather than using string.Trim to do both at once?
> trim strings with string.Trim

- test/ICSharpCode.SharpZipLib.Tests/Base/InflaterDeflaterTests.cs
A small piece of #457 that isn't related to async tests, split off for easier review - use the NUnit [Range] attribute to create a set of tests for different compression levels, rather than just having one test that loops itself internally.
> In InflaterDeflaterTestSuite, use the Range attribute to test different compression levels

- benchmark/ICSharpCode.SharpZipLib.Benchmark/Zip/ZipInputStream.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Zip/ZipOutputStream.cs
(And move the allocation of the read buffer out of the benchmark function).
This enables memory allocation diagnostics in the result output, e.g.
```
|               Method |        Job |     Toolchain |     Mean |   Error |  StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |----------- |-------------- |---------:|--------:|--------:|------:|------:|------:|------:|----------:|
| WriteZipOutputStream | Job-ZVUVIV | .NET Core 2.1 | 700.4 ms | 3.39 ms | 3.18 ms |  1.00 |     - |     - |     - | 354.09 KB |
| WriteZipOutputStream | Job-DWFYDH | .NET Core 3.1 | 716.9 ms | 4.67 ms | 3.90 ms |  1.02 |     - |     - |     - | 354.08 KB |
| WriteZipOutputStream | Job-RVPCBW |        net461 | 701.0 ms | 1.57 ms | 1.47 ms |  1.00 |     - |     - |     - | 360.28 KB |
``` …
> Add [MemoryDiagnoser] to the zip input/output stream benchmark classes

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
refs #78, #124 
Add a variant of FastZip.CreateZip that takes a 'leaveOpen' parameter which controls whether the outputStream is disposed.
We can't really change the behaviour of the existing CreateZip stream variant at this point as it would be a breaking change, so this seems next best?
> Add a variant of FastZip.CreateZip with a leaveOpen parameter to control output stream disposal

- src/ICSharpCode.SharpZipLib/Lzw/LzwConstants.cs
The ```LzwConstants``` class has multiple CA1707 (```Identifiers should not contain underscores```) warnings from FxCop, but as they're public fields and renaming them would be a breaking change (and they might be named like thay because they're copied from some other spec?), this just suppresses the warning rather than doing anything with the names.
There are several similar analyzer warnings, but i'm putting this one in its own PR so i can also query about ```LzwConstants``` being a sealed class rather than a static class -> not sure if changing that would count as an ABI break, but #351 does that change in ```GZipConstants``` so.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source …
> Suppress CA1707 warnings from LzwConstants

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
Found when looking at #454:
The code at:
https://github.com/icsharpcode/SharpZipLib/blob/f36ca373206340a25b1d3bb226acc7b679128a7c/src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs#L330
for writing entries when the header information is known tries to take account of the crypto header overhead, but only does so for ZipCrypto encrypted entries - it uses the wrong values for AES entries.
Also, the code for building the Zip64 extra data at:
https://github.com/icsharpcode/SharpZipLib/blob/f36ca373206340a25b1d3bb226acc7b679128a7c/src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs#L375
doesn't take account of that overhead at all, which seems to also produce incorrect archives.
~~The~~
```
// TODO: Refactor header writing.  Its done in several places.
```
~~becomes a bit more true with the …
> In ZipOutputStream.PutNextEntry, account for AES overhead when calculating compressed entry size

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
I found out that deleting empty directory entry from ZipFile and then adding it back causes an exception while trying to add to `updateIndex` dictionary - because checking for existing element uses transformed `entity.Name` while adding uses its original value. Also directory name gets transformed as file name and ending slash gets removed therefore those too values are not same especially in directory case.
`Entry.Name` is already transformed file name so it shouldn't be transformed twice. So I replaced all such accesses to use entry.Name or transformed string-filename.
Fixes #82
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the …
> Don't convert entry.Name twice when accessing updateIndex

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/WindowsNameTransformHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEntryFactoryHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipNameTransformHandling.cs
This should allow all tests to pass on both *nix and windows.
The current outstanding bug with ZipEntry file names not being automatically cleaned has been moved to it's own test, as this is a known (although unwanted) behaviour of the current state the code base is in.
By doing this we should be able to have failing tests prevent PRs from being merged in a more controlled manner.
Fixes #481 
> Fix tests and ZipEntry DateTime Kind

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
refs #405: Add simple extra versions of FastZip.CreateZip that take file/directory filters as instances of IScanFilter rather than strings.
No unit tests yet (There don't seem to be any tests for ExtendedPathFilter either?)
A possible small api compatibility issue: if you have a call like
```csharp
zippy.CreateZip(tempZip.Filename, tempDir.Fullpath, true, null, null);
```
(as in an existing unit test I had to change), the two null literals for the filter parameters are ambiguous between the existing ```string``` overload and the new ```IScanFilter``` overload, which could possibly need a change to avoid?
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open …
> Add variants of FastZip.CreateZip that take filters as IScanFilter instead of strings

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipNameTransform.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Ref: the discussions about name transforming/cleaning when creating zips:
An experiment into giving ZipOutputStream an INameTransform to (optionally) use to transform file paths, to see what it might look like.
A bit more heavyweight that just having a clean function to call, but more flexible (if that's useful), and fits in more with ZipFile and FastZip?
Defaults to a minimized transform that just strips path roots and puts slashes in the appropriate format (copied from the existing versions and trimmed a bit basically).
ZipEntry.Name is read-only after creation, so it ends up transforming the name twice when doing the local/central headers, rather than just doing it once.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be …
> Give ZipOutputStream an INameTransform property, and use it to transform the names of newly added entries

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
Change ZipFile.TestLocalHeader to use entry.CompressionMethodForHeader rather than CompressionMethod, to handle the two being different for AES encrypted entries.
Fixes #317 
> Change ZipFile.TestLocalHeader to use entry.CompressionMethodForHeader rather than entry.CompressionMethod

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEncryptionMethod.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
Provide a means of enabling AES encryption when creating zips with FastZip (by settings the AESKeySize of the entries it creates prior to giving them to ZipOutputStream).
Notes:
- I added a new mode enum in its own file rather than in FastZip.cs (easy to merge if needed).
- I'm not sure if the encryption mode should have a 'None' option, given that the setting only applies if the password property has been set seperately?
- ~~The call to TestArchive in the unit tests is commented out because of #317~~ 
> Support AES encryption in FastZip.CreateZip

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
> Fix warnings about missing doc comment in FastZip.CreateZip

- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
Now that the fix for ZipEntry name cleaning has been merged, the test that expected it to not be cleaned should be altered to expect a positive result.
> Expect ZipEntry clean name test to be positive

- .editorconfig
- .github/workflows/on-push.yml
- .github/workflows/pull-request.yml
- appveyor.yml
- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEntryFactoryHandling.cs
To enable better feedback and integration, this PR adds Github Actions to build and test merges into master and pull requests.
This includes running on `windows`, `macOS` and `linux` platforms and both on .NET Framework (on windows) and .NET Core.
Fixes #434
> Use github workflows for CI

- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
FastZip's ExtractZip method did not raise the ProcessDirectory event when
creating a directory.  There was no way to determine or control when
ExtractZip decided to create a new directory.
(This presented an issue when I tried using ExtractZip in conjunction as part of an installation tool with automatic-rollback functionality; it did not rollback the creation of directories, so the cleanup didn't work correctly.)
NOTE: The logic to raise the event only triggers when the target directory
doesn't already exist in the destination.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT …
> FastZip: Raise ProcessDirectory event for extractions

- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
When I was looking at BZip2 support in zip files, I had an issue where changing ZipEntry.IsCompressionMethodSupported to return true for BZip2 compression caused issues with ZipInputStream, where it went through its read logic and didn't read anything, but also didn't 'fail'.
When i went to make a change to do something about that, I found that calling GetNextEntry() to get an entry compressed with BZip2 compression (without any other changes) caused it to throw, when it attempted to set ZipEntry.CompressionMethod after construction.
This PR Makes 2 changes that might help with that:
1) Change ZipInputStream.GetNextEntry to use the ZipEntry constructor that takes the CompressionMethod as a parameter, rather than setting it afterwards.
2) Change it to use its own …
> Improve the behaviour of ZipInputStream when reading zip entries with unsupported compression methods

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
When looking at #443 I noticed that the encryption streams created in ZipFile.GetOutputStream didn't seem to be getting disposed.
In order to ensure that they are, I think we need to
1) In the CompressionMethod.Deflated case, make the DeflaterOutputStream own the encryption stream, so that they get disposed together.
2) In the CompressionMethod.Stored case, I think it should be safe to return the encryption stream directly in this case rather than creating an intermediate UncompressedStream? (The stream is only used internally so there should be minimum scope for unexpected uses of it).
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the …
> In ZipFile.GetOutputStream, ensure that any created crypto streams are disposed

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
refs my last comment in #317 - TestArchive doesn't seem to consider AES encryption when testing encrypted directory entries (it always uses ```ZipConstants.CryptoHeaderSize```).
This is just a simple change to use the newly added ```EncryptionOverheadSize ``` instead.
I'm not sure what the '+ 2' is allowing for? (empty compressed data overhead? I'm not sure what the comment in the non-encrypted case about not knowing the true size refers to, when directories don't really have a size?)
> Consider AES overhead when testing encrypted folder entries

- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
Prevents files from being written outside of the destination directory when extracted using `TarArchive.ExtractContents`.
Basically the Tar version of #235 
Attempting to extract a file that has a path traversing outside of the `destinationDirectory` will throw and `InvalidNameException` unless explicitly overridden:
```.cs
tarArchive.ExtractContents(destinationDirectory, allowParentTraversal: true);
```
> Restrict path traversal on TarArchive extraction

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
Work in progress changes to wire up BZip2 support in Zip files using the ZipFile API. refs #315 
Notes: 
~~Needs #333 to prevent ZipInputStream breaking if you try to read such an entry with it.~~
~~Needs #422 to reject attempts to add bzip2 compressed entries to ZipOutputStream.~~
Might need some other tweaks.
It does seem to be reading small zip/bzip2 format files produced with 7-zip successfully at least.
> Wire up support for BZip2 compresion in zip files

- test/ICSharpCode.SharpZipLib.Tests/TestSupport/SevenZip.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
When I was looking at the ZipFile/BZip2 changes I was thinking that it might be useful to verify some of those created archives with 7zip in the way it's currently done for testing encrypted archives, so - I thought it might be useful to break the 7zip helper functions out into their own class rather than being inside the ```ZipEncryptionHandling``` test class as a start towards that.
> Move the 7zip helper functions out of ZipEncryptionHandling into their own class, for easier use elsewhere

- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
refs #507 - possible simple way to avoid the issue, by making PutNextEntry throw if the new entry has an AESKeySize set and the stream password hasn't been set.
I made it an InvalidOperationException rather than an ArgumentException with the idea that the operation is invalid when the stream has no password, 
> Make PutNextEntry throw if the entry is AES and no password has been set. 

- .github/workflows/on-push.yml
- .github/workflows/pull-request.yml
Somehow the Codacy Action tagged with v1.0.1 broke, even though we used the explicit version that did work before. Seems to be fixed in v1.1.0 though.
> Fix Codacy Workflows

- src/ICSharpCode.SharpZipLib/Core/PathUtils.cs
- src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipNameTransform.cs
- Use GetRandomFileName() instead of  GetTempFileName()
- Rename  WindowsPathUtils to PathUtils and make a proper static class
- Unify random file name creation into PathUtils
- Do not create new random files before use
Fixes #537 
> Use securely generated random temporary file names

- src/ICSharpCode.SharpZipLib/Encryption/PkzipClassic.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Use a proper RNG for cryptographically important randomness.
Fixes #536 
> Use RNGCryptoServiceProvider for crypto headers

- src/ICSharpCode.SharpZipLib/Checksum/BZip2Crc.cs
- src/ICSharpCode.SharpZipLib/Checksum/Crc32.cs
- src/ICSharpCode.SharpZipLib/Checksum/CrcUtilities.cs
- test/ICSharpCode.SharpZipLib.Tests/Checksum/ChecksumTests.cs
This change replaces the CRC32 update code with a slicing-by-16 implementation that can process 16 bytes at a time. It uses the original byte-by-byte code as a fallback, but also marks that method for aggressive inlining to get rid of overhead from function calls. This reduces the runtime of the BZip and ZLib CRC checksums by about 75%, which is also good for overall I/O.
The performance can be improved even further by using unsafe code to eliminate array bounds checks. While that code isn't included in this PR, the benchmarks for the unsafe code are included below. The code can be found here: https://github.com/nsgomez/SharpZipLib/commit/6a2e9546b42eb4387c0b83619d91aefdcdbc5bc5
While this is my personal GitHub account, I'm submitting this PR in my capacity as a Microsoft employee.
The …
> Improve CRC32 performance

- .github/workflows/release.yml
> Build and publish documentation on release

- .github/workflows/on-push.yml
- .github/workflows/pull-request.yml
- .travis.yml
- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
Also fix the .NET Standard 2.0 target framework moniker: netstandard2.0 instead of netstandard2, see https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks
> Add .NET Standard 2.1 target framework

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipHelperStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
This skips AES calculation for AES encrypted entries to align with AE-2.
Fixes #552 
> skip CRC calculation for AES zip entries

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
Rather trivial, but FxCop (#449) suggests making these functions static as they don't access instance data ([CA1822](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1822?view=vs-2019), may or may not have hypothetically better performance)
> make a couple of private functions static to silence CA1822 analyzer warnings

- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_BZip2/Cmd_BZip2.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_BZip2/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_Checksum/Cmd_Checksum.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_Checksum/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_GZip/Cmd_GZip.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_GZip/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_Tar/Cmd_Tar.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_Tar/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_ZipInfo/Cmd_ZipInfo.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/Cmd_ZipInfo/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/CreateZipFile/CreateZipFile.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/CreateZipFile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/FastZip/FastZip.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/FastZip/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/sz/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/sz/sz.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/unzipfile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/unzipfile/unzipfile.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/viewzipfile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/viewzipfile/viewzipfile.csproj
- samples/ICSharpCode.SharpZipLib.Samples/cs/zf/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/cs/zf/zf.csproj
Part one of the suggestion from #526 - convert the C# sample projects from packages.config to PackageReference format (and delete all the packages.config files)
> Convert the C# sample projects to PackageReference format

- test/ICSharpCode.SharpZipLib.Tests/Base/InflaterDeflaterTests.cs
refs #223 
Basically just adds async versions of the 'InflateDeflateZlib' and 'InflateDeflateNonZlib' tests and shuffles some things about to share some of the test code instead of duplicating it all.
Also changes the tests to use the NUnit 'Range' attribute for testing the different compression levels instead of having one test that loops over all the levels internally (makes the test a bit simpler, also makes each level appear as a seperate test in the results)
> add some basic async unit tests for the inflator/deflator streams

- test/ICSharpCode.SharpZipLib.TestBootstrapper/ICSharpCode.SharpZipLib.TestBootstrapper.csproj
- tools/appveyor-test.ps1
I'm not sure what the intentions are for the bootstrapper app now that the github actions are running the tests directly, but:
I'm getting build warnings (visible in the appveyor build as well) about the bootstrapper app being built as .NET Core 2.0, when the test assembly that it depends on is now built as .NET Core 3.1 and .NET 4.6, so - try fixing that by retargetting it at 3.1 to match.
> Build the test bootstrapper app as netcoreapp3.1 instead of netcoreapp2.0

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
spin off from my question about what exception type it should use in #576 (not sure if there's a more specific exception type about to use, but plain ```Exception``` seems wrong)
> Make ZipAESStream throw ZipException instead of Exception when the AES auth code is wrong

- src/ICSharpCode.SharpZipLib/Core/Exceptions/StreamDecodingException.cs
Just something I noticed while looking at something else.
> Fix typos in the StreamDecodingException doc comments

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipEntryExtensions.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
Due to the way that ZipInputStream is designed, reading entries that are using `Store` compression method and `Descriptor` flag is not possible. This change will throw a `StreamUnsupportedException` instead of failing on incorrect CRC.
Fixes #15 (as much as a fix as is possible for this).
> Throw exception on Store+Descriptor entries

- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs
An offshoot of #576 and related, to add a small extra test for doing async reads on the stream returned from ZipFile.GetInputStream using different compression methods - put in its own PR to make it more self contained
> add a simple async read test for ZipFile

- samples/ICSharpCode.SharpZipLib.Samples/vb/CreateZipFile/CreateZipFile.vbproj
- samples/ICSharpCode.SharpZipLib.Samples/vb/CreateZipFile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/vb/WpfCreateZipFile/WpfCreateZipFile.vbproj
- samples/ICSharpCode.SharpZipLib.Samples/vb/WpfCreateZipFile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/vb/minibzip2/minibzip2.vbproj
- samples/ICSharpCode.SharpZipLib.Samples/vb/minibzip2/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/vb/viewzipfile/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/vb/viewzipfile/viewzipfile.vbproj
- samples/ICSharpCode.SharpZipLib.Samples/vb/zipfiletest/packages.config
- samples/ICSharpCode.SharpZipLib.Samples/vb/zipfiletest/zipfiletest.vbproj
and also update them to use the 1.3.1 package.
> Convert VB sample projects to PackageReference format

- src/ICSharpCode.SharpZipLib/Core/EmptyRefs.cs
- src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs
- src/ICSharpCode.SharpZipLib/Tar/TarEntry.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipExtraData.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
Applies the 'Empty.Array' helper from #501 and uses it in several places that currently use 'new T[0]' 
(the places that have been changed are all places that cause CA1825 suggestions from FxCop, refs #449) 
> Replace uses of new T[0] with Array.Empty<T>

- test/ICSharpCode.SharpZipLib.TestBootstrapper/NuGet.config
- test/ICSharpCode.SharpZipLib.Tests/NuGet.config
I'm not sure if they're actually needed - try to remove them and see.
> Remove the local nuget.config files from the test projects

- .github/workflows/on-push.yml
- .github/workflows/pull-request.yml
Since the `ICSharpCode.SharpZipLib.Tests` project targets `net46` and not `net45`, no tests are currently being run for .NET FW.
This will update the actions to run the tests on windows targets correctly.
> Use net46 as the target framework for windows tests

- .github/workflows/on-push.yml
- .github/workflows/pull-request.yml
- test/ICSharpCode.SharpZipLib.TestBootstrapper/ICSharpCode.SharpZipLib.TestBootstrapper.csproj
- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
Code coverage is currently not being reported. This updates packages and removes the ones not being used, as well as adding upload of coverage reports to Codecov.
> Update test/coverage packages and push to codecov

- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
Second part of #602 for `CreateZipShouldSetTimeOnEntriesFromConstructorTimeSetting`
> pass CreateZip tests that are within time tolerance

- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
This should fix the intermittent test failures in CI due to the password check only comparing a single byte (as per the spec), which have a 1/255 chance of actually matching regardless of password.
Now, it still has a 1/65025 chance of colliding, but hopefully that should be rare enough to not matter.
> test: retry zipcrypto password tests once

- src/ICSharpCode.SharpZipLib/GZip/GZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/DeflaterConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
Just continuing to chip away at the warnings/suggestions from #449 by disabling some more [CA1707](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1707) warnings.
Note: Some of the warnings from ```ZipConstants``` are actually on things that have been marked as ```[Obsolete]```, e,g, ```VERSION_MADE_BY``` - I don't know if there are any plans to remove those any point?
> Suppress some more CA1707 warnings in the Constants classes

- src/ICSharpCode.SharpZipLib/Core/PathUtils.cs
- test/ICSharpCode.SharpZipLib.Tests/Core/CoreTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/SevenZip.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipNameTransformHandling.cs
Fixes #56
This did grow a bit, since a lot of stuff was discovered while working on this.
Prior to this, all tests (and indeed the behaviour) for handling paths just presumed that the platform was Windows.
The core problem method (DropPathRoot) has now been changed to use the framework/platforms path handling methods, but with some special exceptions for .NET < 4.6.2.
This does feel a bit hackish, but I think it's better than the previous method, which was to implement custom code for determining what a root path is. If that code fails to notice something that the OS would consider a absolute path it could lead to vulnerabilities. If this implementation fails to notice it, it would instead throw, which could then be fixed.
And also, since this only happens in older frameworks, in most …
> Simplify DropPathRoot and fix out of bounds issue

- README.md
...instead of appveyor, which no longer has results.
> Change the build status badge to reference github actions

- benchmark/ICSharpCode.SharpZipLib.Benchmark/BZip2/BZip2InputStream.cs
- benchmark/ICSharpCode.SharpZipLib.Benchmark/ICSharpCode.SharpZipLib.Benchmark.csproj
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Program.cs
- src/ICSharpCode.SharpZipLib/BZip2/BZip2InputStream.cs
Hi guys.
Here's the simple approach to get some speed-up on BZip2 decompression. Rotation loop (`yy[j] = yy[j -1]`) is here vectorized automatically, i.e. by means of `Vector<byte>` instead of e.g. `Vector128<byte>` tied to a specific platform. The API is available from the .NET Core/Standard 2.1, however the real gain starts in .NET Core 3.
First commits add .NET Core 3.1 as a target platform for performance tests and such a test for BZip2 decompression. The last commit is the actual vectorization. Here are some results from two Intel machines (one on Windows and one on a rather antique MacBook Air).
---
**Without** vectorization:
First machine
```
|         Method |        Job |     Toolchain |    Mean |    Error |   StdDev | Ratio |
|--------------- |----------- |-------------- …
```
> Bzip input stream simple vectorization

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
Possible extra trivial version of #576, just for testing and a potential quick fix (whereby it doesn't attempt to actually be async)
> Implement ReadAsync in ZipAESStream, extra simple version

- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
- src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
> security fixes for v1.3.2

- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipNameTransformHandling.cs
> fix the expected/actual value ordering in a few unit test asserts

- .github/workflows/build-test.yml
Only upload code coverage for windows in an attempt to fix the broken code coverage diffs on PRs
> Limit code coverage to windows CI

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
refs #590 
This would be a breaking API change, but - is there actually a need for the Password property to be on DeflaterOutputStream, given that it only applies to creating encrypted Zip files? (the property isn't actually referenced by DeflaterOutputStream anyway, only from ZipOutputStream)
Related:
The ```InitializePassword``` and ```InitializeAESPassword``` functions in DeflaterOutputStream only seem to be called from ZipOutputStream as well, though they set the (presently private) ```cryptoTransform_``` member as well, so moving them as well would need a further change.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the …
> Move the Password property from DeflaterOutputStream into ZipOutputStream

- .gitignore
- benchmark/ICSharpCode.SharpZipLib.Benchmark/Zip/ZipOutputStream.cs
> add an async version of the WriteZipOutputStream benchmark

- .github/workflows/build-test.yml
- test/ICSharpCode.SharpZipLib.Tests/BZip2/Bzip2Tests.cs
- test/ICSharpCode.SharpZipLib.Tests/Base/InflaterDeflaterTests.cs
- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
This prevents the code coverage to fluctuate depending on the compressibility of the random data.
It also replaces the `opencover` + `coverlet.collector` method with `dotcover`.
The testing and code coverage for windows was split to another job instead of bundling it together with macos/linux with a lot of conditional steps.
> Fix unstable tests and switch to dotcover

- src/ICSharpCode.SharpZipLib/Core/PathUtils.cs
- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
In #622 the temporary file path was changed to use `Path.GetRandomFileName()` instead of `Path.GetTempFileName()`, which resulted in the current working directory being used for storing the translated tar files while creating archives.
This instead uses the `PathUtils.GetTempFileName()` that was created for this purpose.
Fixes #644
> fix(tar): create translated files in temp

- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
> docs(zip): fix ZipStrings typo

- src/ICSharpCode.SharpZipLib/Zip/ZipEntry.cs
I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License.
> docs(zip): fix slash names in CleanName comment

- src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarArchiveTests.cs
Fixes an issue where `TarArchive.ExtractContents` would cause an `InvalidNameException` when the destination dir ended with `/`.
Adds additional tests for combinations of tar file names and extraction destination paths.
> fix(tar): permit slashed output dir

- test/ICSharpCode.SharpZipLib.Tests/BZip2/Bzip2Tests.cs
- test/ICSharpCode.SharpZipLib.Tests/Base/InflaterDeflaterTests.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarArchiveTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/StringTesting.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
This replaces all usage of `Random` in the tests with deterministic pseudo random data that should yield the same coverage regardless of runs and if new tests are added (which was the case before).
It also refactors and homogenize the tests a bit, with clearer asserts and labels for non-obvious arguments.
> test: repeatability and refactoring

- src/ICSharpCode.SharpZipLib/Zip/ZipExtraData.cs
This is the TagId change from #470 split into a stand alone change.
> fix(zip): use ushort for ITaggedData.TagID

- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/PassthroughTests.cs
I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License.
> feat(zip): enable ZipOuputStream to write precompressed files

- .github/workflows/build-test.yml
The `windows-latest` tag was changed from `windows-2019` to `windows-2022` (ref https://github.com/github/docs/issues/15603).
Unfortunately, that means it does no longer contain any runtime/targeting pack for deprecated .NET frameworks (`net45` in our case). This changes the CI to instead target the latest working version (`windows-2019`).
Perhaps a supported runtime scope update is due, but that's another discussion.
> ci: use server 2019 for win builds

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
Fixing what seems like a merge artifact (7 years ago!) that fails the `LocalHeaderTest`s when an archive is using Zip64 and Descriptors, and the size in the local Zip64 extra data is set to `0` (which is per spec).
This also replaces the bitwise flag checks with a helper method to increase legibility (not mixing boolean and bitwise logic).
Fixes #735
> fix(zip): dont fail test on 0 sizes and descriptor

- src/ICSharpCode.SharpZipLib/Zip/ZipConstants.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/ZipTesting.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/FastZipHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/PassthroughTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipEncryptionHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
This allows for skipping (some of) the local header tests performed when reading `ZipFile` entries.
Example:
```cs
using (var zipFile = new ZipFile(inputFile)){
zipFile.SkipLocalEntryTestsOnLocate = true;
foreach (var entry in zipFile)
{
// ...
}
}
```
Also included are some refactoring done when investigating this. Mostly to make the code path easier to follow and provide better errors when things go wrong.
> feat(zip): make it possible to skip header tests

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFormat.cs
In #736, the header tests were changed to allow for `0` being passed as the Zip64 sizes when testing the archive. That is actually the correct value as per the spec, and hence this updates the output of `ZipFormat.WriteLocalHeader` to write `0` when using descriptors together with Zip64.
Fixes #744
> fix(zip): 0 in zip64 local sizes using descriptors

- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Streams.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/StreamHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipStreamAsyncTests.cs
The async version of `PutNextEntry` tries to read the target streams position to be able to correctly patch the sizes, even if the stream doesn't support seeking. This causes a `NotSupported` exception to be thrown when used with common non-seekable target streams.
Fixes #731.
> fix(zip): skip reading position for non-seekable async streams

- src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs
The Rfc2898DeriveBytes constructor used is called out as insecure in NET 7, because it’s insecure to use defaults for the number of iterations and hashing algorithm. The fix is to pass those (secure) values in the versions of .NET that support it.
> Fix security weakness for compilation in .NET 7

- src/ICSharpCode.SharpZipLib/Tar/TarExtendedHeaderReader.cs
Fixes #383, but is not the most elegant solution. `TarExtendedHeaderReader` should probably be rewritten from scratch.
> fix(tar): read full extended headers

- src/ICSharpCode.SharpZipLib/Encryption/PkzipClassic.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
Replace insecure obsolete method (new RNGCryptoServiceProvider()) with RandomNumberGenerator.Create() in PkzipClassic, ZipFile and ZipOutputStream.
> fix: replace uses of obsolete method `RNGCryptoServiceProvider`

- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipAsyncTests.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipStreamAsyncTests.cs
Follow up to #574 that implements `DisposeAsync` and "true" async write support to `GzipOutputStream`.
> feat(gzip): add GzipOutputStream async support

- .github/workflows/build-test.yml
- benchmark/ICSharpCode.SharpZipLib.Benchmark/ICSharpCode.SharpZipLib.Benchmark.csproj
- src/ICSharpCode.SharpZipLib/Encryption/ZipAESStream.cs
- src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs
- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
this branch contains changes needed for the upcoming release, mainly related to .NET 6
The new target frameworks will be:
- .NET Standard 2.0 (for .NET framework 4.6.2+)
- .NET Standard 2.1 (general support for all but .NET framework)
- .NET 6.0 (new LTS)
the main issue stems from the fact that the AES auth code reading is handled inside a class inheriting from `CryptoStream`. For that to work correctly, the reads cannot be bypassed by more efficient code (which is what is happening in the .NET 6 version of `CryptoStream`).
In fact, the entire `ZIPAESStream` should probably just be removed altogether, since it seems to just be a work around for having the auth code appended to the input stream. this can be handled much easier in the TransformLastBlock method of ZipAESTransform.
that …
> prepare for v1.4.0

- docs/help/docfx.json
- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
fix circular references in `inheritdocs` and target framework.
> docs: fix circular refs and target fw

- src/ICSharpCode.SharpZipLib/Tar/TarBuffer.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarInputStreamTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Utils.cs
When reading a tar file using `TarBuffer` and the EOF was reached before a full record could be read, the `ReadRecordAsync` method still treats it as a successful read, by assuming the rest of the buffer just contained zeros.
This is not necessarily the case with a SharedArray buffer, which it currently uses. This PR makes sure that the rest of the buffer is cleared before returning.
Fixes #782.
> fix(tar): clear rest of buffer when eof is reached

- test/ICSharpCode.SharpZipLib.Tests/Tar/TarBufferTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarInputStreamTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Tar/TarTests.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/RingBuffer.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs
When dealing with compression, different methods of reducing the size is used depending on the source content. This will cause a different amount of code paths to be used/covered in the tests for every run.
This PR ensures that all uses of `Random` in the tests use a fixed seed, and as such will always cover the same amount of code.
Without this, the code coverage changes for PRs will fluctuate, and sometimes cause the overall coverage to go down even though the added changes have 100% coverage.
> tests: make test coverage consistent

- src/ICSharpCode.SharpZipLib/Tar/TarInputStream.cs
- src/ICSharpCode.SharpZipLib/Tar/TarOutputStream.cs
> fix(tar): use sync codepath on sync methods

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/FastZip.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipFormat.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipStrings.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/GeneralHandling.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipStringsTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipTests.cs
This PR fixes some issues that were present in #592 but wasn't detected before the release of v1.4.0.
In general, it goes a bit further in trying to make the string encoding easy and predictable to use.
It also has tests for the most common usages of the API to make sure it both works and feels straightforward to use.
The changes in the API are slightly breaking from v1.4.0, but only where the API could be misused in confusing ways. It should not require any minor version bump, but should be released ASAP to limit the effect.
Fixes #777.
Fixes #776.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is …
> fix(zip): cleanup/fix of StringCodec

- src/ICSharpCode.SharpZipLib/ICSharpCode.SharpZipLib.csproj
New patch release that mainly fixes issues with the changes in v1.4.0.
Further iteration on the StringCodec API, since the released version was confusing to use and in some cases could not be used without causing deprecation warnings.
* 🐛 [#778](https://github.com/icsharpcode/SharpZipLib/pull/778) `zip` __cleanup/fix of StringCodec__ by [_nils måsén_](https://github.com/piksel)
Two issues that could cause deadlocks was found in v1.4.0, one due to a typo in the async implementation and one due to a buffer not being cleared.
* 🐛 [#791](https://github.com/icsharpcode/SharpZipLib/pull/791) `tar` __use sync codepath on sync methods__ by [_Lars Hanisch_](https://github.com/flensrocker)
* 🐛 [#789](https://github.com/icsharpcode/SharpZipLib/pull/789) `tar` __clear rest of buffer when eof is …
> release v1.4.1

- src/ICSharpCode.SharpZipLib/Zip/ZipInputStream.cs
When merging #778, some debug logging were left in. This removes it, since it was never meant to be checked in in the first place.
Fixes #807.
> fix(zip): remove leftover console logging

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/TestSupport/Streams.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipStreamAsyncTests.cs
This PR fixes the async finishing of entries in `ZipOutputStream`. The initial problem was that there was a sneaky `base.Finish()` call in `WriteEntryFooter` which in turn wrote synchronously to the output stream when called.
Additionally, `DeflateOutputSteam.AsyncDispose` was not included when targeting .NET 6 due to the preprocessor constants for `NETSTANDARD2_1_OR_GREATER` not being defined.
This also adds tests that ensures that writing zip streams can be done wholly async, without calling any of the output streams synchronous methods.
Fixes #801 
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is …
> zip: finish stream async when async

- test/ICSharpCode.SharpZipLib.Tests/ICSharpCode.SharpZipLib.Tests.csproj
This allows nunit3 tests to run on .NET 7.
> test: update deps for net7 support

- src/ICSharpCode.SharpZipLib/Tar/TarBuffer.cs
- src/ICSharpCode.SharpZipLib/Tar/TarHeader.cs
- src/ICSharpCode.SharpZipLib/Tar/TarInputStream.cs
Implicitly include async overrides on `NETCOREAPP3_1_OR_GREATER` to include them when targeting .NET 6.
> fix(tar): enable async overrides on net6

- src/ICSharpCode.SharpZipLib/GZip/GzipInputStream.cs
- src/ICSharpCode.SharpZipLib/GZip/GzipOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
- src/ICSharpCode.SharpZipLib/Zip/ZipOutputStream.cs
- test/ICSharpCode.SharpZipLib.Tests/GZip/GZipAsyncTests.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipStreamAsyncTests.cs
Using the previously implemented parts of async deflate/ZipOutputStream would only work as long as the compressed size was lower than the internal deflater buffer.
This fix adds async writing to `DeflaterOutputStream` and `GzipOutputStream`, and allows `ZipOutputStream` to empty it's buffer using asynchronous writes.
This also extends the test for `ZipOutputStream` to try with a larger source buffer and adds a test for `GzipOutputStream` for wholly-async IO.
Additionally, `GzipOutputStream.ModifiedTime` can now also be set. This was added to allow the tests to yield a predicable output.
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the …
> fix(zip): fully implement async deflate

- src/ICSharpCode.SharpZipLib/Zip/Compression/Streams/DeflaterOutputStream.cs
DocFX is unable to find the docs for the `Stream.WriteAsync` override in `DeflaterOutputStream`. This explicitly sets the doc comments to the upstream docs to re-enable docs generation.
> docs: fix missing async override docs

- .github/workflows/build-test.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
This will simply update the versions of workflow action dependencies to non-deprecated versions.
> chore(ci): update workflow actions

- src/ICSharpCode.SharpZipLib/Core/PathUtils.cs
- test/ICSharpCode.SharpZipLib.Tests/Zip/ZipFileHandling.cs
Since the APPNOTE allows for zip files to contain files without a file name (useful for piping into a zip file), this ought to be allowed for SharpZipLib as well. This will fix the issue by handling a null value being returned by `Path.GetPathRoot`.
Supersedes #687.
> fix(zip): avoid throwing on empty file name

- src/ICSharpCode.SharpZipLib/Zip/ZipFile.cs
> Fix ZipFile constructor breaking change
